export const BasicData = [
  {
    title: "Books",
    totalItems: Math.round(Math.random() * 9999),
    percentage: Math.round(Math.random() * 99),
    color: "#ff4545",
    history: [
      {
        name: "Page A",
        uv: Math.round(Math.random() * 9999),
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: Math.round(Math.random() * 9999),
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: Math.round(Math.random() * 9999),
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: Math.round(Math.random() * 9999),
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: Math.round(Math.random() * 9999),
        pv: 4800,
        amt: 2181,
      },
      {
        name: "Page F",
        uv: Math.round(Math.random() * 9999),
        pv: 3800,
        amt: 2500,
      },
      {
        name: "Page G",
        uv: Math.round(Math.random() * 9999),
        pv: 4300,
        amt: 2100,
      },
    ],
  },
  {
    title: "Pages",
    totalItems: Math.round(Math.random() * 9999),
    pv: 500,
    amt: 500,
    percentage: Math.round(Math.random() * 99),
    sign: Math.random() * 10 > 3,
    color: "#ffaa00",
    history: [
      {
        name: "Page A",
        uv: Math.round(Math.random() * 9999),
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: Math.round(Math.random() * 9999),
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: Math.round(Math.random() * 9999),
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: Math.round(Math.random() * 9999),
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: Math.round(Math.random() * 9999),
        pv: 4800,
        amt: 2181,
      },
      {
        name: "Page F",
        uv: Math.round(Math.random() * 9999),
        pv: 3800,
        amt: 2500,
      },
      {
        name: "Page G",
        uv: Math.round(Math.random() * 9999),
        pv: 4300,
        amt: 2100,
      },
    ],
  },
  {
    title: "Comments",
    totalItems: Math.round(Math.random() * 9999),
    pv: 500,
    amt: 500,
    percentage: Math.round(Math.random() * 99),
    sign: Math.random() * 10 > 3,
    color: "#00AAFF",
    history: [
      {
        name: "Page A",
        uv: Math.round(Math.random() * 9999),
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: Math.round(Math.random() * 9999),
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: Math.round(Math.random() * 9999),
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: Math.round(Math.random() * 9999),
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: Math.round(Math.random() * 9999),
        pv: 4800,
        amt: 2181,
      },
      {
        name: "Page F",
        uv: Math.round(Math.random() * 9999),
        pv: 3800,
        amt: 2500,
      },
      {
        name: "Page G",
        uv: Math.round(Math.random() * 9999),
        pv: 4300,
        amt: 2100,
      },
    ],
  },
  {
    title: "Subscribers",
    totalItems: Math.round(Math.random() * 9999),
    pv: 500,
    amt: 500,
    percentage: Math.round(Math.random() * 99),
    sign: Math.random() * 10 > 3,
    color: "#55FF55",
    history: [
      {
        name: "Page A",
        uv: Math.round(Math.random() * 9999),
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: Math.round(Math.random() * 9999),
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: Math.round(Math.random() * 9999),
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: Math.round(Math.random() * 9999),
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: Math.round(Math.random() * 9999),
        pv: 4800,
        amt: 2181,
      },
      {
        name: "Page F",
        uv: Math.round(Math.random() * 9999),
        pv: 3800,
        amt: 2500,
      },
      {
        name: "Page G",
        uv: Math.round(Math.random() * 9999),
        pv: 4300,
        amt: 2100,
      },
    ],
  },
];
